INSERT INTO league (country, league_name) VALUES ('Hiszpania', 'La Liga');
INSERT INTO league (country, league_name) VALUES ('Anglia', 'Premier League');
INSERT INTO league (country, league_name) VALUES ('Niemcy', 'Bundesliga');
INSERT INTO league (country, league_name) VALUES ('Włochy', 'Serie A');
INSERT INTO league (country, league_name) VALUES ('Francja', 'Ligue 1');
INSERT INTO league (country, league_name) VALUES ('Portugalia', 'Primeira Liga');
INSERT INTO league (country, league_name) VALUES ('Holandia', 'Eredivisie');
INSERT INTO league (country, league_name) VALUES ('Belgia', 'Jupiler League');
INSERT INTO league (country, league_name) VALUES ('Grecja', 'Super League');
INSERT INTO league (country, league_name) VALUES ('Polska', 'LOTTO Ekstraklasa');

INSERT INTO team (country, club_name) VALUES ('Hiszpania', 'Alavés');
INSERT INTO team (country, club_name) VALUES ('Hiszpania', 'Athletic Bilbao');
INSERT INTO team (country, club_name) VALUES ('Hiszpania', 'Atlético Madrid');
INSERT INTO team (country, club_name) VALUES ('Hiszpania', 'Barcelona');
INSERT INTO team (country, club_name) VALUES ('Hiszpania', 'Celta Vigo');
INSERT INTO team (country, club_name) VALUES ('Hiszpania', 'Eibar');
INSERT INTO team (country, club_name) VALUES ('Hiszpania', 'Espanyol');
INSERT INTO team (country, club_name) VALUES ('Hiszpania', 'Getafe');
INSERT INTO team (country, club_name) VALUES ('Hiszpania', 'Girona');
INSERT INTO team (country, club_name) VALUES ('Hiszpania', 'Huesca');
INSERT INTO team (country, club_name) VALUES ('Hiszpania', 'Leganés');
INSERT INTO team (country, club_name) VALUES ('Hiszpania', 'Levante');
INSERT INTO team (country, club_name) VALUES ('Hiszpania', 'Rayo Vallecano');
INSERT INTO team (country, club_name) VALUES ('Hiszpania', 'Real Betis');
INSERT INTO team (country, club_name) VALUES ('Hiszpania', 'Real Madrid');
INSERT INTO team (country, club_name) VALUES ('Hiszpania', 'Real Sociedad');
INSERT INTO team (country, club_name) VALUES ('Hiszpania', 'Sevilla');
INSERT INTO team (country, club_name) VALUES ('Hiszpania', 'Valencia');
INSERT INTO team (country, club_name) VALUES ('Hiszpania', 'Valladolid');
INSERT INTO team (country, club_name) VALUES ('Hiszpania', 'Villarreal CF');

INSERT INTO team (country, club_name) VALUES ('Anglia', 'Manchester City');
INSERT INTO team (country, club_name) VALUES ('Anglia', 'Manchester United');
INSERT INTO team (country, club_name) VALUES ('Anglia', 'Tottenham Hotspur');
INSERT INTO team (country, club_name) VALUES ('Anglia', 'Liverpool FC');
INSERT INTO team (country, club_name) VALUES ('Anglia', 'Chelsea');
INSERT INTO team (country, club_name) VALUES ('Anglia', 'Burnley');
INSERT INTO team (country, club_name) VALUES ('Anglia', 'Everton');
INSERT INTO team (country, club_name) VALUES ('Anglia', 'Leicester City');
INSERT INTO team (country, club_name) VALUES ('Anglia', 'Newcastle United');
INSERT INTO team (country, club_name) VALUES ('Anglia', 'Crystal Palace');
INSERT INTO team (country, club_name) VALUES ('Anglia', 'Bournemouth');
INSERT INTO team (country, club_name) VALUES ('Anglia', 'West Ham United');
INSERT INTO team (country, club_name) VALUES ('Anglia', 'Watford');
INSERT INTO team (country, club_name) VALUES ('Anglia', 'Brighton & Hove Albion');
INSERT INTO team (country, club_name) VALUES ('Anglia', 'Huddersfield Town');
INSERT INTO team (country, club_name) VALUES ('Anglia', 'Southampton');
INSERT INTO team (country, club_name) VALUES ('Anglia', 'Wolverhampton Wanderers');
INSERT INTO team (country, club_name) VALUES ('Anglia', 'Cardiff City');
INSERT INTO team (country, club_name) VALUES ('Anglia', 'Fulham');
INSERT INTO team (country, club_name) VALUES ('Anglia', 'Arsenal');

INSERT INTO team (country, club_name) VALUES ('Niemcy', 'FC Augsburg');
INSERT INTO team (country, club_name) VALUES ('Niemcy', 'Hertha BSC');
INSERT INTO team (country, club_name) VALUES ('Niemcy', 'Werder Bremen');
INSERT INTO team (country, club_name) VALUES ('Niemcy', 'Borussia Dortmund');
INSERT INTO team (country, club_name) VALUES ('Niemcy', 'Fortuna Düsseldorf');
INSERT INTO team (country, club_name) VALUES ('Niemcy', 'Eintracht Frankfurt');
INSERT INTO team (country, club_name) VALUES ('Niemcy', 'SC Freiburg');
INSERT INTO team (country, club_name) VALUES ('Niemcy', 'Hannover 96');
INSERT INTO team (country, club_name) VALUES ('Niemcy', '1899 Hoffenheim');
INSERT INTO team (country, club_name) VALUES ('Niemcy', 'RB Leipzig');
INSERT INTO team (country, club_name) VALUES ('Niemcy', 'Bayer Leverkusen');
INSERT INTO team (country, club_name) VALUES ('Niemcy', 'Mainz 05');
INSERT INTO team (country, club_name) VALUES ('Niemcy', 'Borussia Mönchengladbach');
INSERT INTO team (country, club_name) VALUES ('Niemcy', 'Bayern Munich');
INSERT INTO team (country, club_name) VALUES ('Niemcy', '1. FC Nürnberg');
INSERT INTO team (country, club_name) VALUES ('Niemcy', 'Schalke 04');
INSERT INTO team (country, club_name) VALUES ('Niemcy', 'VfB Stuttgart');
INSERT INTO team (country, club_name) VALUES ('Niemcy', 'VfL Wolfsburg');

INSERT INTO team (country, club_name) VALUES ('Włochy', 'Juventus FC');
INSERT INTO team (country, club_name) VALUES ('Włochy', 'SSC Napoli');
INSERT INTO team (country, club_name) VALUES ('Włochy', 'AS Roma');
INSERT INTO team (country, club_name) VALUES ('Włochy', 'Inter Mediolan');
INSERT INTO team (country, club_name) VALUES ('Włochy', 'SS Lazio');
INSERT INTO team (country, club_name) VALUES ('Włochy', 'AC Milan');
INSERT INTO team (country, club_name) VALUES ('Włochy', 'Atalanta BC');
INSERT INTO team (country, club_name) VALUES ('Włochy', 'ACF Fiorentina');
INSERT INTO team (country, club_name) VALUES ('Włochy', 'Torino FC');
INSERT INTO team (country, club_name) VALUES ('Włochy', 'UC Sampdoria');
INSERT INTO team (country, club_name) VALUES ('Włochy', 'US Sassuolo');
INSERT INTO team (country, club_name) VALUES ('Włochy', 'Genoa CFC');
INSERT INTO team (country, club_name) VALUES ('Włochy', 'Chievo Verona');
INSERT INTO team (country, club_name) VALUES ('Włochy', 'Udinese Calcio');
INSERT INTO team (country, club_name) VALUES ('Włochy', 'Bologna FC');
INSERT INTO team (country, club_name) VALUES ('Włochy', 'Cagliari Calcio');
INSERT INTO team (country, club_name) VALUES ('Włochy', 'SPAL');
INSERT INTO team (country, club_name) VALUES ('Włochy', 'Empoli FC');
INSERT INTO team (country, club_name) VALUES ('Włochy', 'Parma FC');
INSERT INTO team (country, club_name) VALUES ('Włochy', 'Frosinone');

INSERT INTO team (country, club_name) VALUES ('Francja', 'Paris Saint-Germain');
INSERT INTO team (country, club_name) VALUES ('Francja', 'AS Monaco');
INSERT INTO team (country, club_name) VALUES ('Francja', 'Olympique Lyon');
INSERT INTO team (country, club_name) VALUES ('Francja', 'Olympique Marsylia');
INSERT INTO team (country, club_name) VALUES ('Francja', 'Stade Rennes');
INSERT INTO team (country, club_name) VALUES ('Francja', 'Girondins Bordeaux');
INSERT INTO team (country, club_name) VALUES ('Francja', 'AS Saint-Étienne');
INSERT INTO team (country, club_name) VALUES ('Francja', 'OGC Nice');
INSERT INTO team (country, club_name) VALUES ('Francja', 'FC Nantes');
INSERT INTO team (country, club_name) VALUES ('Francja', 'Montpellier HSC');
INSERT INTO team (country, club_name) VALUES ('Francja', 'Dijon FCO');
INSERT INTO team (country, club_name) VALUES ('Francja', 'EA Guingamp');
INSERT INTO team (country, club_name) VALUES ('Francja', 'Amiens SC');
INSERT INTO team (country, club_name) VALUES ('Francja', 'Angers SCO');
INSERT INTO team (country, club_name) VALUES ('Francja', 'RC Strasbourg');
INSERT INTO team (country, club_name) VALUES ('Francja', 'SM Caen');
INSERT INTO team (country, club_name) VALUES ('Francja', 'Lille OSC');
INSERT INTO team (country, club_name) VALUES ('Francja', 'Toulouse FC');
INSERT INTO team (country, club_name) VALUES ('Francja', 'Stade de Reims');
INSERT INTO team (country, club_name) VALUES ('Francja', 'Nîmes Olympique');

INSERT INTO team (country, club_name) VALUES ('Portugalia', 'Belenenses SAD');
INSERT INTO team (country, club_name) VALUES ('Portugalia', 'Benfica');
INSERT INTO team (country, club_name) VALUES ('Portugalia', 'Boavista');
INSERT INTO team (country, club_name) VALUES ('Portugalia', 'Braga');
INSERT INTO team (country, club_name) VALUES ('Portugalia', 'Chaves');
INSERT INTO team (country, club_name) VALUES ('Portugalia', 'Desportivo das Aves');
INSERT INTO team (country, club_name) VALUES ('Portugalia', 'Feirense');
INSERT INTO team (country, club_name) VALUES ('Portugalia', 'Marítimo');
INSERT INTO team (country, club_name) VALUES ('Portugalia', 'Moreirense');
INSERT INTO team (country, club_name) VALUES ('Portugalia', 'Nacional');
INSERT INTO team (country, club_name) VALUES ('Portugalia', 'Portimonense');
INSERT INTO team (country, club_name) VALUES ('Portugalia', 'Porto');
INSERT INTO team (country, club_name) VALUES ('Portugalia', 'Rio Ave');
INSERT INTO team (country, club_name) VALUES ('Portugalia', 'Santa Clara');
INSERT INTO team (country, club_name) VALUES ('Portugalia', 'Sporting CP');
INSERT INTO team (country, club_name) VALUES ('Portugalia', 'Tondela');
INSERT INTO team (country, club_name) VALUES ('Portugalia', 'Vitória de Guimarães');
INSERT INTO team (country, club_name) VALUES ('Portugalia', 'Vitória de Setúbal');

INSERT INTO team (country, club_name) VALUES ('Holandia', 'PSV Eindhoven');
INSERT INTO team (country, club_name) VALUES ('Holandia', 'Ajax');
INSERT INTO team (country, club_name) VALUES ('Holandia', 'AZ Alkmaar');
INSERT INTO team (country, club_name) VALUES ('Holandia', 'Feyenoord');
INSERT INTO team (country, club_name) VALUES ('Holandia', 'Utrecht');
INSERT INTO team (country, club_name) VALUES ('Holandia', 'Vitesse');
INSERT INTO team (country, club_name) VALUES ('Holandia', 'ADO Den Haag');
INSERT INTO team (country, club_name) VALUES ('Holandia', 'Heerenveen');
INSERT INTO team (country, club_name) VALUES ('Holandia', 'PEC Zwolle');
INSERT INTO team (country, club_name) VALUES ('Holandia', 'Heracles');
INSERT INTO team (country, club_name) VALUES ('Holandia', 'Excelsior');
INSERT INTO team (country, club_name) VALUES ('Holandia', 'Groningen');
INSERT INTO team (country, club_name) VALUES ('Holandia', 'Willem II');
INSERT INTO team (country, club_name) VALUES ('Holandia', 'NAC Breda');
INSERT INTO team (country, club_name) VALUES ('Holandia', 'VVV-Venlo');
INSERT INTO team (country, club_name) VALUES ('Holandia', 'Fortuna Sittard');
INSERT INTO team (country, club_name) VALUES ('Holandia', 'De Graafschap');
INSERT INTO team (country, club_name) VALUES ('Holandia', 'Emmen');

INSERT INTO team (country, club_name) VALUES ('Belgia', 'Club Brugge');
INSERT INTO team (country, club_name) VALUES ('Belgia', 'Standard Liège');
INSERT INTO team (country, club_name) VALUES ('Belgia', 'RSC Anderlecht');
INSERT INTO team (country, club_name) VALUES ('Belgia', 'KAA Gent');
INSERT INTO team (country, club_name) VALUES ('Belgia', 'KRC Genk');
INSERT INTO team (country, club_name) VALUES ('Belgia', 'Charleroi');
INSERT INTO team (country, club_name) VALUES ('Belgia', 'Kortrijk');
INSERT INTO team (country, club_name) VALUES ('Belgia', 'Royal Antwerp');
INSERT INTO team (country, club_name) VALUES ('Belgia', 'SV Zulte Waregem');
INSERT INTO team (country, club_name) VALUES ('Belgia', 'Sint-Truiden');
INSERT INTO team (country, club_name) VALUES ('Belgia', 'KV Oostende');
INSERT INTO team (country, club_name) VALUES ('Belgia', 'Waasland-Beveren');
INSERT INTO team (country, club_name) VALUES ('Belgia', 'Lokeren');
INSERT INTO team (country, club_name) VALUES ('Belgia', 'Mouscron');
INSERT INTO team (country, club_name) VALUES ('Belgia', 'KAS Eupen');
INSERT INTO team (country, club_name) VALUES ('Belgia', 'Cercle Brugge');

INSERT INTO team (country, club_name) VALUES ('Grecja', 'AEK Ateny');
INSERT INTO team (country, club_name) VALUES ('Grecja', 'PAOK FC');
INSERT INTO team (country, club_name) VALUES ('Grecja', 'Olympiakos SFP');
INSERT INTO team (country, club_name) VALUES ('Grecja', 'PAE Atromitos');
INSERT INTO team (country, club_name) VALUES ('Grecja', 'Asteras Tripolis');
INSERT INTO team (country, club_name) VALUES ('Grecja', 'AO Ksanti');
INSERT INTO team (country, club_name) VALUES ('Grecja', 'Panionios GSS');
INSERT INTO team (country, club_name) VALUES ('Grecja', 'Panetolikos');
INSERT INTO team (country, club_name) VALUES ('Grecja', 'PAS Janina');
INSERT INTO team (country, club_name) VALUES ('Grecja', 'APO Lewadiakos');
INSERT INTO team (country, club_name) VALUES ('Grecja', 'Panathinaikos AO');
INSERT INTO team (country, club_name) VALUES ('Grecja', 'AE Larisa');
INSERT INTO team (country, club_name) VALUES ('Grecja', 'PAS Lamia 1964');
INSERT INTO team (country, club_name) VALUES ('Grecja', 'Apollon Smyrnis');
INSERT INTO team (country, club_name) VALUES ('Grecja', 'OFI 1925');
INSERT INTO team (country, club_name) VALUES ('Grecja', 'Aris FC');

INSERT INTO team (country, club_name) VALUES ('Polska', 'Legia Warszawa');
INSERT INTO team (country, club_name) VALUES ('Polska', 'Jagiellonia Białystok');
INSERT INTO team (country, club_name) VALUES ('Polska', 'Lech Poznań');
INSERT INTO team (country, club_name) VALUES ('Polska', 'Górnik Zabrze');
INSERT INTO team (country, club_name) VALUES ('Polska', 'Wisła Płock');
INSERT INTO team (country, club_name) VALUES ('Polska', 'Wisła Kraków');
INSERT INTO team (country, club_name) VALUES ('Polska', 'Zagłębie Lubin');
INSERT INTO team (country, club_name) VALUES ('Polska', 'Korona Kielce');
INSERT INTO team (country, club_name) VALUES ('Polska', 'Cracovia');
INSERT INTO team (country, club_name) VALUES ('Polska', 'Śląsk Wrocław');
INSERT INTO team (country, club_name) VALUES ('Polska', 'Pogoń Szczecin');
INSERT INTO team (country, club_name) VALUES ('Polska', 'Arka Gdynia');
INSERT INTO team (country, club_name) VALUES ('Polska', 'Lechia Gdańsk');
INSERT INTO team (country, club_name) VALUES ('Polska', 'Piast Gliwice');
INSERT INTO team (country, club_name) VALUES ('Polska', 'Miedź Legnica');
INSERT INTO team (country, club_name) VALUES ('Polska', 'Zagłębie Sosnowiec');
